spring:
  profiles:
    active: local

---

spring:
  profiles: local
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9091/mem:test;MODE=MYSQL;INIT=RUNSCRIPT FROM 'classpath:/sql/ddl_h2.sql'
      username: sa
      password:
      driver-class-name: org.h2.Driver

  session:
    store-type: redis

    redis:
      namespace: callbus:session

  redis:
    host: localhost
    port: 6379

fcm:
  key:
    path: push-test-3035f-firebase-adminsdk-xhjoq-d2c8e79be3.json
    client-token: evVxPHaiTt6o37_of1l8ha:APA91bHPstR-28IPqZSrZ674qL2KFS1KsZ2hOEhLc8DsQ69QARag1N04WIj8lAUJDL_zwdCokz-rsJFHKnakJ24jUcGDDikxXvdvoMV3VpHE4qWbESaCAj_HhXvZV5r8RE0VyQoH8Xxz
    server-key: AAAAHC0s3BI:APA91bF3rhTp7hj7gign_8sjxyO6SBocZdvOi7cLnsTitTbqn4CzHOTJfq5LkdFoktnF0K0QGjAPApvRodRtCJBtcjQ_MZSb7CTjG_BdKi_cWS6qJMbJP0ruU_3NTkZeCiiNPQpG2X8-

expire:
  client:
    certNum: 86400
    session: 31449600

server:
  port: 80

---

spring:
  profiles: set1
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: jdbc:mariadb://database-1.ccjvntw75bzx.us-east-2.rds.amazonaws.com:3306/test
    username: admin
    password: callbus12
    driver-class-name: org.mariadb.jdbc.Driver

  session:
    store-type: redis

    redis:
      namespace: callbus:session


  redis:
    host: ec2-18-219-111-129.us-east-2.compute.amazonaws.com
    port: 6379

fcm:
  key:
    path: push-test-3035f-firebase-adminsdk-xhjoq-d2c8e79be3.json
    client-token: evVxPHaiTt6o37_of1l8ha:APA91bHPstR-28IPqZSrZ674qL2KFS1KsZ2hOEhLc8DsQ69QARag1N04WIj8lAUJDL_zwdCokz-rsJFHKnakJ24jUcGDDikxXvdvoMV3VpHE4qWbESaCAj_HhXvZV5r8RE0VyQoH8Xxz
    server-key: AAAAHC0s3BI:APA91bF3rhTp7hj7gign_8sjxyO6SBocZdvOi7cLnsTitTbqn4CzHOTJfq5LkdFoktnF0K0QGjAPApvRodRtCJBtcjQ_MZSb7CTjG_BdKi_cWS6qJMbJP0ruU_3NTkZeCiiNPQpG2X8-

expire:
  client:
    certNum: 86400
    session: 31449600

server:
  port: 8081

---

spring:
  profiles: set2
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mariadb://database-1.ccjvntw75bzx.us-east-2.rds.amazonaws.com:3306/test
    username: admin
    password: callbus12
    driver-class-name: org.mariadb.jdbc.Driver

  session:
    store-type: redis

    redis:
      namespace: callbus:session

  redis:
    host: ec2-18-219-111-129.us-east-2.compute.amazonaws.com
    port: 6379


fcm:
  key:
    path: push-test-3035f-firebase-adminsdk-xhjoq-d2c8e79be3.json
    client-token: evVxPHaiTt6o37_of1l8ha:APA91bHPstR-28IPqZSrZ674qL2KFS1KsZ2hOEhLc8DsQ69QARag1N04WIj8lAUJDL_zwdCokz-rsJFHKnakJ24jUcGDDikxXvdvoMV3VpHE4qWbESaCAj_HhXvZV5r8RE0VyQoH8Xxz
    server-key: AAAAHC0s3BI:APA91bF3rhTp7hj7gign_8sjxyO6SBocZdvOi7cLnsTitTbqn4CzHOTJfq5LkdFoktnF0K0QGjAPApvRodRtCJBtcjQ_MZSb7CTjG_BdKi_cWS6qJMbJP0ruU_3NTkZeCiiNPQpG2X8-

expire:
  client:
    certNum: 86400
    session: 31449600

server:
  port: 8082
