spring:
  datasource:
    url: jdbc:mariadb://localhost:3306?test
    username: kyh
    password: dydgus92
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    port: 6379
    host: localhost



fcm:
  key:
    path: push-test-3035f-firebase-adminsdk-xhjoq-d2c8e79be3.json
    client-token: evVxPHaiTt6o37_of1l8ha:APA91bHPstR-28IPqZSrZ674qL2KFS1KsZ2hOEhLc8DsQ69QARag1N04WIj8lAUJDL_zwdCokz-rsJFHKnakJ24jUcGDDikxXvdvoMV3VpHE4qWbESaCAj_HhXvZV5r8RE0VyQoH8Xxz
    server-key: AIzaSyD0OuBmS4uuh4ksELi4l2y5CmJHDwLtuw8

expire:
  client:
    certNum: 86400

